/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class loginpage extends javax.swing.JFrame {
int score=0;
    /**
     * Creates new form loginpage
     */
    public loginpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        d1 = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        continu = new javax.swing.JButton();
        d2 = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        j2 = new javax.swing.JFrame();
        jLabel5 = new javax.swing.JLabel();
        start = new javax.swing.JButton();
        j3 = new javax.swing.JFrame();
        jLabel6 = new javax.swing.JLabel();
        r11 = new javax.swing.JRadioButton();
        r12 = new javax.swing.JRadioButton();
        r13 = new javax.swing.JRadioButton();
        r14 = new javax.swing.JRadioButton();
        nextb = new javax.swing.JButton();
        r15 = new javax.swing.JRadioButton();
        bg1 = new javax.swing.ButtonGroup();
        j4 = new javax.swing.JFrame();
        r16 = new javax.swing.JRadioButton();
        nextb1 = new javax.swing.JButton();
        r17 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        r18 = new javax.swing.JRadioButton();
        r19 = new javax.swing.JRadioButton();
        r20 = new javax.swing.JRadioButton();
        j8 = new javax.swing.JFrame();
        YOURSCORE = new javax.swing.JButton();
        result = new javax.swing.JLabel();
        closeb = new javax.swing.JButton();
        startagain = new javax.swing.JButton();
        j5 = new javax.swing.JFrame();
        r21 = new javax.swing.JRadioButton();
        r22 = new javax.swing.JRadioButton();
        nextb2 = new javax.swing.JButton();
        r23 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        r24 = new javax.swing.JRadioButton();
        r25 = new javax.swing.JRadioButton();
        j6 = new javax.swing.JFrame();
        r26 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        r27 = new javax.swing.JRadioButton();
        r28 = new javax.swing.JRadioButton();
        r29 = new javax.swing.JRadioButton();
        r30 = new javax.swing.JRadioButton();
        nextb3 = new javax.swing.JButton();
        j7 = new javax.swing.JFrame();
        nextb4 = new javax.swing.JButton();
        r31 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        r32 = new javax.swing.JRadioButton();
        r33 = new javax.swing.JRadioButton();
        r34 = new javax.swing.JRadioButton();
        r35 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        login = new javax.swing.JButton();
        p = new javax.swing.JPasswordField();

        d1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36)); // NOI18N
        jLabel3.setText("WELCOME");
        d1.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));

        continu.setText("continue....");
        continu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuActionPerformed(evt);
            }
        });
        d1.getContentPane().add(continu, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 120, 40));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setText("Try Again!");

        back.setText("back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout d2Layout = new javax.swing.GroupLayout(d2.getContentPane());
        d2.getContentPane().setLayout(d2Layout);
        d2Layout.setHorizontalGroup(
            d2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(d2Layout.createSequentialGroup()
                .addGroup(d2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(d2Layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(d2Layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(270, Short.MAX_VALUE))
        );
        d2Layout.setVerticalGroup(
            d2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, d2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("you will have 5 questions. Each question carries 5 mark each. if your answer is wrong -1 mark will be deducted.");

        start.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        start.setText("start..");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout j2Layout = new javax.swing.GroupLayout(j2.getContentPane());
        j2.getContentPane().setLayout(j2Layout);
        j2Layout.setHorizontalGroup(
            j2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j2Layout.createSequentialGroup()
                .addGroup(j2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(j2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(j2Layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(217, Short.MAX_VALUE))
        );
        j2Layout.setVerticalGroup(
            j2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j2Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("1-who is the father of nation");

        bg1.add(r11);
        r11.setText("jawaharlal nehru");
        r11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r11ActionPerformed(evt);
            }
        });

        bg1.add(r12);
        r12.setText("M K Gandhi");
        r12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r12ActionPerformed(evt);
            }
        });

        bg1.add(r13);
        r13.setText("Lal bahadur shastri");

        bg1.add(r14);
        r14.setText("Sardar vallabhai patel");

        nextb.setText("next");
        nextb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextbActionPerformed(evt);
            }
        });

        bg1.add(r15);
        r15.setText("proceed without answering");

        javax.swing.GroupLayout j3Layout = new javax.swing.GroupLayout(j3.getContentPane());
        j3.getContentPane().setLayout(j3Layout);
        j3Layout.setHorizontalGroup(
            j3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j3Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(j3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(j3Layout.createSequentialGroup()
                        .addGroup(j3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(r11, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r13)
                            .addComponent(r15))
                        .addGap(38, 38, 38)
                        .addGroup(j3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nextb, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r14)
                            .addComponent(r12))))
                .addContainerGap(384, Short.MAX_VALUE))
        );
        j3Layout.setVerticalGroup(
            j3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j3Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(j3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r11)
                    .addComponent(r12))
                .addGap(42, 42, 42)
                .addGroup(j3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r13)
                    .addComponent(r14))
                .addGap(24, 24, 24)
                .addGroup(j3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r15)
                    .addComponent(nextb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        bg1.add(r16);
        r16.setText("thales");

        nextb1.setText("next");
        nextb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextb1ActionPerformed(evt);
            }
        });

        bg1.add(r17);
        r17.setText("proceed without answering");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("2-who is known as the father of mathematics");

        bg1.add(r18);
        r18.setText("aryabhatta");
        r18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r18ActionPerformed(evt);
            }
        });

        bg1.add(r19);
        r19.setText("pythagoras");
        r19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r19ActionPerformed(evt);
            }
        });

        bg1.add(r20);
        r20.setText("archimedes");

        javax.swing.GroupLayout j4Layout = new javax.swing.GroupLayout(j4.getContentPane());
        j4.getContentPane().setLayout(j4Layout);
        j4Layout.setHorizontalGroup(
            j4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j4Layout.createSequentialGroup()
                .addGroup(j4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(j4Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(j4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(j4Layout.createSequentialGroup()
                                .addComponent(r18, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(r19))
                            .addGroup(j4Layout.createSequentialGroup()
                                .addComponent(r17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                                .addComponent(nextb1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(j4Layout.createSequentialGroup()
                                .addComponent(r20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(r16))))
                    .addGroup(j4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        j4Layout.setVerticalGroup(
            j4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j4Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(j4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r18)
                    .addComponent(r19))
                .addGap(42, 42, 42)
                .addGroup(j4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r20)
                    .addComponent(r16))
                .addGap(24, 24, 24)
                .addGroup(j4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r17)
                    .addComponent(nextb1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        nextb1.getAccessibleContext().setAccessibleParent(this);

        YOURSCORE.setText("YOUR  SCORE");
        YOURSCORE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YOURSCOREActionPerformed(evt);
            }
        });

        result.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        closeb.setText("close");
        closeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebActionPerformed(evt);
            }
        });

        startagain.setText("Start Again");
        startagain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startagainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout j8Layout = new javax.swing.GroupLayout(j8.getContentPane());
        j8.getContentPane().setLayout(j8Layout);
        j8Layout.setHorizontalGroup(
            j8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j8Layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(closeb, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(j8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(YOURSCORE, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .addComponent(result, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(startagain)
                .addContainerGap(208, Short.MAX_VALUE))
        );
        j8Layout.setVerticalGroup(
            j8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j8Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(j8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(j8Layout.createSequentialGroup()
                        .addComponent(YOURSCORE, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(closeb))
                    .addComponent(startagain))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        bg1.add(r21);
        r21.setText("copper");

        bg1.add(r22);
        r22.setText("aluminium");

        nextb2.setText("next");
        nextb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextb2ActionPerformed(evt);
            }
        });

        bg1.add(r23);
        r23.setText("proceed without answering");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("4.The metal whose salts are sensitive to light is.?");

        bg1.add(r24);
        r24.setText("zinc");
        r24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r24ActionPerformed(evt);
            }
        });

        bg1.add(r25);
        r25.setText("silver");
        r25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r25ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout j5Layout = new javax.swing.GroupLayout(j5.getContentPane());
        j5.getContentPane().setLayout(j5Layout);
        j5Layout.setHorizontalGroup(
            j5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j5Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(j5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(j5Layout.createSequentialGroup()
                        .addComponent(r23)
                        .addGap(104, 104, 104)
                        .addComponent(nextb2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(j5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(j5Layout.createSequentialGroup()
                            .addComponent(r21)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(r22))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, j5Layout.createSequentialGroup()
                            .addComponent(r24, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(r25))
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        j5Layout.setVerticalGroup(
            j5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, j5Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(j5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r24)
                    .addComponent(r25))
                .addGap(42, 42, 42)
                .addGroup(j5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r21)
                    .addComponent(r22))
                .addGap(62, 62, 62)
                .addGroup(j5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r23)
                    .addComponent(nextb2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90))
        );

        bg1.add(r26);
        r26.setText("proceed without answering");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("D.D.T was invented by _________");

        bg1.add(r27);
        r27.setText("mosley");
        r27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r27ActionPerformed(evt);
            }
        });

        bg1.add(r28);
        r28.setText("rudeolf");
        r28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r28ActionPerformed(evt);
            }
        });

        bg1.add(r29);
        r29.setText("Karl Benz");

        bg1.add(r30);
        r30.setText("Dalton");

        nextb3.setText("next");
        nextb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextb3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout j6Layout = new javax.swing.GroupLayout(j6.getContentPane());
        j6.getContentPane().setLayout(j6Layout);
        j6Layout.setHorizontalGroup(
            j6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j6Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(j6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(j6Layout.createSequentialGroup()
                        .addComponent(r26)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(j6Layout.createSequentialGroup()
                        .addGroup(j6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(j6Layout.createSequentialGroup()
                                .addGroup(j6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(r29)
                                    .addComponent(r27, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(j6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(j6Layout.createSequentialGroup()
                                        .addGap(99, 99, 99)
                                        .addComponent(nextb3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, j6Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(j6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(r28, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(r30, javax.swing.GroupLayout.Alignment.TRAILING))))))
                        .addContainerGap(212, Short.MAX_VALUE))))
        );
        j6Layout.setVerticalGroup(
            j6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, j6Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(j6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r27)
                    .addComponent(r28))
                .addGap(56, 56, 56)
                .addGroup(j6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r29)
                    .addComponent(r30))
                .addGap(46, 46, 46)
                .addGroup(j6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r26)
                    .addComponent(nextb3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
        );

        nextb4.setText("next");
        nextb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextb4ActionPerformed(evt);
            }
        });

        bg1.add(r31);
        r31.setText("proceed without answering");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("5-Which is considered as the biggest port of India?");

        bg1.add(r32);
        r32.setText("kolkata");
        r32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r32ActionPerformed(evt);
            }
        });

        bg1.add(r33);
        r33.setText("cochin");
        r33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r33ActionPerformed(evt);
            }
        });

        bg1.add(r34);
        r34.setText("chennai");

        bg1.add(r35);
        r35.setText("mumbai");
        r35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r35ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout j7Layout = new javax.swing.GroupLayout(j7.getContentPane());
        j7.getContentPane().setLayout(j7Layout);
        j7Layout.setHorizontalGroup(
            j7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j7Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addGroup(j7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(j7Layout.createSequentialGroup()
                        .addGroup(j7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(r32, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r34))
                        .addGap(219, 219, 219)
                        .addGroup(j7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(r33)
                            .addComponent(r35)))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(j7Layout.createSequentialGroup()
                        .addComponent(r31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nextb4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(232, Short.MAX_VALUE))
        );
        j7Layout.setVerticalGroup(
            j7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j7Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(j7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r32)
                    .addComponent(r33))
                .addGap(48, 48, 48)
                .addGroup(j7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r35)
                    .addComponent(r34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(j7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r31)
                    .addComponent(nextb4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(127, 127, 127))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PASSWORD");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel2.setText("USERNAME");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        t1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        login.setText("LOGIN");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(144, 144, 144)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t1)
                            .addComponent(p, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(t1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
String uid=t1.getText();
String pwd=new String(p.getPassword());
if(uid.equals("admin")&&pwd.equals("1234"))
d1.setVisible(true);
else
d2.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_loginActionPerformed

    private void continuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuActionPerformed
    d1.dispose(); 
    j2.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_continuActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
d2.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
j3.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_startActionPerformed

    private void r11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r11ActionPerformed

    private void r12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r12ActionPerformed

    private void nextbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextbActionPerformed

if(r12.isSelected()==true)
    score+=5;
else if(r15.isSelected()==true)
    score+=0;// TODO add your handling code here:
else 
    score+=-1;
j4.setVisible(true);
    }//GEN-LAST:event_nextbActionPerformed

    private void nextb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextb1ActionPerformed
if(r20.isSelected()==true)
    score+=5;
else if(r17.isSelected()==true)
    score+=0;// TODO add your handling code here:
else 
    score+=-1;
j5.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_nextb1ActionPerformed

    private void r18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r18ActionPerformed

    private void r19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r19ActionPerformed

    private void YOURSCOREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YOURSCOREActionPerformed
result.setText(""+score);
score=0;// TODO add your handling code here:
    }//GEN-LAST:event_YOURSCOREActionPerformed

    private void startagainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startagainActionPerformed
j8.dispose();
j4.dispose();
j3.dispose();
j5.dispose();
j6.dispose();
j7.dispose();
result.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_startagainActionPerformed

    private void nextb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextb2ActionPerformed
   if(r25.isSelected()==true)
    score+=5;
else if(r23.isSelected()==true)
    score+=0;// TODO add your handling code here:
else 
    score+=-1;
j6.setVisible(true);     // TODO add your handling code here:
    }//GEN-LAST:event_nextb2ActionPerformed

    private void r24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r24ActionPerformed

    private void r25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r25ActionPerformed

    private void r27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r27ActionPerformed

    private void r28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r28ActionPerformed

    private void nextb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextb3ActionPerformed
     if(r30.isSelected()==true)
    score+=5;
else if(r26.isSelected()==true)
    score+=0;// TODO add your handling code here:
else 
    score+=-1;
j7.setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_nextb3ActionPerformed

    private void nextb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextb4ActionPerformed
        if(r35.isSelected()==true)
    score+=5;
else if(r31.isSelected()==true)
    score+=0;// TODO add your handling code here:
else 
    score+=-1;
j8.setVisible(true);     // TODO add your handling code here:
    }//GEN-LAST:event_nextb4ActionPerformed

    private void r32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r32ActionPerformed

    private void r33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r33ActionPerformed

    private void r35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r35ActionPerformed

    private void closebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_closebActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
   /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginpage().setVisible(true);
             
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton YOURSCORE;
    private javax.swing.JButton back;
    private javax.swing.ButtonGroup bg1;
    private javax.swing.JButton closeb;
    private javax.swing.JButton continu;
    private javax.swing.JDialog d1;
    private javax.swing.JDialog d2;
    private javax.swing.JFrame j2;
    private javax.swing.JFrame j3;
    private javax.swing.JFrame j4;
    private javax.swing.JFrame j5;
    private javax.swing.JFrame j6;
    private javax.swing.JFrame j7;
    private javax.swing.JFrame j8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton login;
    private javax.swing.JButton nextb;
    private javax.swing.JButton nextb1;
    private javax.swing.JButton nextb2;
    private javax.swing.JButton nextb3;
    private javax.swing.JButton nextb4;
    private javax.swing.JPasswordField p;
    private javax.swing.JRadioButton r11;
    private javax.swing.JRadioButton r12;
    private javax.swing.JRadioButton r13;
    private javax.swing.JRadioButton r14;
    private javax.swing.JRadioButton r15;
    private javax.swing.JRadioButton r16;
    private javax.swing.JRadioButton r17;
    private javax.swing.JRadioButton r18;
    private javax.swing.JRadioButton r19;
    private javax.swing.JRadioButton r20;
    private javax.swing.JRadioButton r21;
    private javax.swing.JRadioButton r22;
    private javax.swing.JRadioButton r23;
    private javax.swing.JRadioButton r24;
    private javax.swing.JRadioButton r25;
    private javax.swing.JRadioButton r26;
    private javax.swing.JRadioButton r27;
    private javax.swing.JRadioButton r28;
    private javax.swing.JRadioButton r29;
    private javax.swing.JRadioButton r30;
    private javax.swing.JRadioButton r31;
    private javax.swing.JRadioButton r32;
    private javax.swing.JRadioButton r33;
    private javax.swing.JRadioButton r34;
    private javax.swing.JRadioButton r35;
    private javax.swing.JLabel result;
    private javax.swing.JButton start;
    private javax.swing.JButton startagain;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables
}
